In [10]:
# to get dimension of the array
arr = np.array([[1,2],[2,6]]) 
print(arr) 
print (arr.ndim) 

[[1 2]
 [2 6]]
2


In [11]:
# to get size
arr = np.array([[1,3],[2,4]])
print(arr.itemsize)

8


In [12]:
# to reshape
import numpy as np  
a = np.array([[1,2],[3,4],[5,6]])  
print("printing the original array..")  
print(a)  
a=a.reshape(2,3)  
print("printing the reshaped array..")  
print(a)  

printing the original array..
[[1 2]
 [3 4]
 [5 6]]
printing the reshaped array..
[[1 2 3]
 [4 5 6]]


In [13]:
# it prints an array containing zeroes 
arr = np.zeros((3,2), dtype = int)  
print(arr)  

[[0 0]
 [0 0]
 [0 0]]


In [14]:
# it prints an array containing ones

arr= np.ones((4,3),dtype=int) 
print(arr) 

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [15]:
# creation of ndarray using iterable object
list = [0,2,4,6]  
it = iter(list)  
x = np.fromiter(it, dtype = float)  
print(x)  
print(type(x))  

[0. 2. 4. 6.]
<class 'numpy.ndarray'>


In [16]:
# using specifiedbuffer

import numpy as np  
l = b'hellooo'  
print(type(l))  
a = np.frombuffer(l, dtype = "S1")  
print(a)  


<class 'bytes'>
[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']


In [ ]:
# creates evenly spaced array using given interval
arr = np.arange(0,10,2,float)  
print(arr)  

In [20]:
# empty array
x = np.empty([3,2], dtype = int) 
print(x) 

[[1 2]
 [3 4]
 [5 6]]


In [22]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print ('First array:' ) 
print(a) 
print(np.append(a, [7,8,9]) ) 

First array:
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# random numbers array
e = np.random.random((2, 2))
print(e) 

In [ ]:
# to get datatype
a = np.array([(1,2,3)])
print(a.dtype)

In [5]:
# max, min and sum
a= np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())

1
3
6


In [7]:
a=np.full((4,3),16)
print(a) 

[[16 16 16]
 [16 16 16]
 [16 16 16]
 [16 16 16]]


In [9]:
b=np.full_like(a, 14)
print(b) 

[[14 14 14]
 [14 14 14]
 [14 14 14]
 [14 14 14]]


In [10]:
c=np.identity(3)
print(c) 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
d=np.sin(a) 
print(d) 

[[-0.28790332 -0.28790332 -0.28790332]
 [-0.28790332 -0.28790332 -0.28790332]
 [-0.28790332 -0.28790332 -0.28790332]
 [-0.28790332 -0.28790332 -0.28790332]]


In [12]:
e=np.cos(d) 
print (e) 

[[0.95884132 0.95884132 0.95884132]
 [0.95884132 0.95884132 0.95884132]
 [0.95884132 0.95884132 0.95884132]
 [0.95884132 0.95884132 0.95884132]]


In [13]:
a=np.array([1,2,4])
b=np.array([4,5,6])
c=np.matmul(a, b) 
print(c) 

38
